-- This is a sql file of nigerian universities both state,
-- Federal and Private Universities.
-- Designed by Akinkuade Akinlabi Olakunle
-- 08149708214
-- https://www.facebook.com/akinkuadeakinlabi
--
-- Host: 127.0.0.1
-- Generation Time: Jan 26, 2019 at 10:24 PM
-- Server version: 10.1.30-MariaDB
-- PHP Version: 7.2.2

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `scholarship`
--

-- --------------------------------------------------------

--
-- Table structure for table `universities`
--

CREATE TABLE `universities` (
  `id` int(255) NOT NULL,
  `name` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `universities`
--

INSERT INTO `universities` (`id`, `name`) VALUES
(1, 'Abia State University of Uturu'),
(2, 'Abti-American University, Yola'),
(3, 'Abubakar Tafawa Balewa University, Bauchi'),
(4, 'Achievers University, Owo'),
(5, 'Adamawa State University Mubi.'),
(6, 'Adekunle Ajasin University, Akungba.'),
(7, 'African University of Science & Technology, Abuja'),
(8, 'Ahmadu Bello University Zaria'),
(9, 'Ajayi Crowther University, Ibadan'),
(10, 'Akwa Ibom State University of Technology, Uyo.'),
(11, 'Al-Hikmah University, Ilorin'),
(12, 'Ambrose Ali University, Ekpoma.'),
(13, 'Anambra State University of Science and Technology, Calabar.'),
(14, 'Babcock University,Illshan-Remo'),
(15, 'Bayero University, Kano'),
(16, 'Bells University of Technology, Otta'),
(17, 'Benson Idahosa University,Benin City'),
(18, 'Benue State University, Makurdi.'),
(19, 'Bingham University, New Karu'),
(20, 'Bowen University, Iwo'),
(21, 'Buka Abba Ibrahim University, Yobe.'),
(22, 'Caleb University, Lagos'),
(23, 'Caritas University, Enugu'),
(24, 'CETEP City University, Ibadan'),
(25, 'Covenant University Ota'),
(26, 'Crawford University Igbesa'),
(27, 'Crescent University,'),
(28, 'Cross River State University of Science and Technology, Calabar.'),
(29, 'Delta State University Abraka.'),
(30, 'Ebonyi State University, Abakaliki.'),
(31, 'Enugu State University of Science and Technology, Enugu'),
(32, 'Federal University Ndufu Alike, Ebonyi.'),
(33, 'Federal University of Agriculture, Abeokuta.'),
(34, 'Federal University of Petroleum Recourses, Effurun.'),
(35, 'Federal University of Technology, Akure.'),
(36, 'Federal University of Technology, Minna.'),
(37, 'Federal University of Technology, Owerri.'),
(38, 'Federal University of Technology, Yola.'),
(39, 'Federal University Wukari, Taraba.'),
(40, 'Federal University, Dutse, Jigawa.'),
(41, 'Federal University, Dutsin?Ma-Katsina, Katsina'),
(42, 'Federal University, Lafia, Nasarawa'),
(43, 'Federal University, Lokoga, Kogi.'),
(44, 'Federal University, Otuoke, Bayelsa.'),
(45, 'Fountain Unveristy,Oshogbo'),
(46, 'Gombe State Univeristy, Gombe'),
(47, 'Ibrahim Badamasi Babangida University, Lapai'),
(48, 'Igbinedion University Okada'),
(49, 'Imo State University, Owerri'),
(50, 'Joseph Ayo Babalola University, Ikeji-Arakeji'),
(51, 'Kaduna State University, Kaduna'),
(52, 'Kano State University of Technology Wudil'),
(53, 'Katsina State University, Katsina'),
(54, 'Katsina University, Katsina'),
(55, 'Kebbi State University, Kebbi'),
(56, 'Kogi State University Anyigb'),
(57, 'Ladoke Akintola University of Technology, Ogbomoso'),
(58, 'Lagos State University Ojo, Lagos.'),
(59, 'Lead City University, Ibadan'),
(60, 'Madonna University, Okija'),
(61, 'Micheal Okpara University of Agriculture, Umudike.'),
(62, 'Nasarawa State University, Keffi'),
(63, 'National Open University of Nigeria, Lagos.'),
(64, 'Niger Delta Unversity, Yenagoa.'),
(65, 'Nigerian Defence Accademy, Kaduna.'),
(66, 'Nnamdi Azikiwe University, Akwa.'),
(67, 'Novena University, Ogume'),
(68, 'Obafemi Awolowo University, Ile Ife.'),
(69, 'Obong University'),
(70, 'Olabisi Onabanjo University Ago-Iwoye .'),
(71, 'Osun State University, Oshogbo.'),
(72, 'Pan African University, Lagos'),
(73, 'Plateau State University, Bokkos'),
(74, 'Redeemer?s University, Mowe'),
(75, 'Renaissance University, Enugu'),
(76, 'Rivers State University of Science & Technology'),
(77, 'Salem University, Lokoja'),
(78, 'Tai Solarin Univ. of Education, Ijebu-Ode'),
(79, 'Tansian University, Umunya'),
(80, 'University of Abuja, Gwagwalada.'),
(81, 'University of Ado-Ekiti'),
(82, 'University of Agriculture, Makurdi.'),
(83, 'University of Benin.'),
(84, 'University of Calabar.'),
(85, 'University of Education, Ikere Ekiti'),
(86, 'University of Ibadan'),
(87, 'University of Ilorin'),
(88, 'University of Jos.'),
(89, 'University of Lagos.'),
(90, 'University of Maiduguri.'),
(91, 'University of Mkar, Mkar'),
(92, 'University of Nigeria, Nsukka.'),
(93, 'University of Port Harcourt.'),
(94, 'University of Uyo.'),
(95, 'Usuman Danfodiyo University.'),
(96, 'Veritas University'),
(97, 'Wesley Univ. of Science & Tech.,Ondo'),
(98, 'Western Delta University, Oghara'),
(99, 'Wukari Jubilee University'),
(100, 'Abia State University of Uturu'),
(101, 'Abti-American University, Yola'),
(102, 'Abubakar Tafawa Balewa University, Bauchi'),
(103, 'Achievers University, Owo'),
(104, 'Adamawa State University Mubi.'),
(105, 'Adekunle Ajasin University, Akungba.'),
(106, 'African University of Science & Technology, Abuja'),
(107, 'Ahmadu Bello University Zaria'),
(108, 'Ajayi Crowther University, Ibadan'),
(109, 'Akwa Ibom State University of Technology, Uyo.'),
(110, 'Al-Hikmah University, Ilorin'),
(111, 'Ambrose Ali University, Ekpoma.'),
(112, 'Anambra State University of Science and Technology, Calabar.'),
(113, 'Babcock University,Illshan-Remo'),
(114, 'Bayero University, Kano'),
(115, 'Bells University of Technology, Otta'),
(116, 'Benson Idahosa University,Benin City'),
(117, 'Benue State University, Makurdi.'),
(118, 'Bingham University, New Karu'),
(119, 'Bowen University, Iwo'),
(120, 'Buka Abba Ibrahim University, Yobe.'),
(121, 'Caleb University, Lagos'),
(122, 'Caritas University, Enugu'),
(123, 'CETEP City University, Ibadan'),
(124, 'Covenant University Ota'),
(125, 'Crawford University Igbesa'),
(126, 'Crescent University,'),
(127, 'Cross River State University of Science and Technology, Calabar.'),
(128, 'Delta State University Abraka.'),
(129, 'Ebonyi State University, Abakaliki.'),
(130, 'Enugu State University of Science and Technology, Enugu'),
(131, 'Federal University Ndufu Alike, Ebonyi.'),
(132, 'Federal University of Agriculture, Abeokuta.'),
(133, 'Federal University of Petroleum Recourses, Effurun.'),
(134, 'Federal University of Technology, Akure.'),
(135, 'Federal University of Technology, Minna.'),
(136, 'Federal University of Technology, Owerri.'),
(137, 'Federal University of Technology, Yola.'),
(138, 'Federal University Wukari, Taraba.'),
(139, 'Federal University, Dutse, Jigawa.'),
(140, 'Federal University, Dutsin?Ma-Katsina, Katsina'),
(141, 'Federal University, Lafia, Nasarawa'),
(142, 'Federal University, Lokoga, Kogi.'),
(143, 'Federal University, Otuoke, Bayelsa.'),
(144, 'Fountain Unveristy,Oshogbo'),
(145, 'Gombe State Univeristy, Gombe'),
(146, 'Ibrahim Badamasi Babangida University, Lapai'),
(147, 'Igbinedion University Okada'),
(148, 'Imo State University, Owerri'),
(149, 'Joseph Ayo Babalola University, Ikeji-Arakeji'),
(150, 'Kaduna State University, Kaduna'),
(151, 'Kano State University of Technology Wudil'),
(152, 'Katsina State University, Katsina'),
(153, 'Katsina University, Katsina'),
(154, 'Kebbi State University, Kebbi'),
(155, 'Kogi State University Anyigb'),
(156, 'Ladoke Akintola University of Technology, Ogbomoso'),
(157, 'Lagos State University Ojo, Lagos.'),
(158, 'Lead City University, Ibadan'),
(159, 'Madonna University, Okija'),
(160, 'Micheal Okpara University of Agriculture, Umudike.'),
(161, 'Nasarawa State University, Keffi'),
(162, 'National Open University of Nigeria, Lagos.'),
(163, 'Niger Delta Unversity, Yenagoa.'),
(164, 'Nigerian Defence Accademy, Kaduna.'),
(165, 'Nnamdi Azikiwe University, Akwa.'),
(166, 'Novena University, Ogume'),
(167, 'Obafemi Awolowo University, Ile Ife.'),
(168, 'Obong University'),
(169, 'Olabisi Onabanjo University Ago-Iwoye .'),
(170, 'Osun State University, Oshogbo.'),
(171, 'Pan African University, Lagos'),
(172, 'Plateau State University, Bokkos'),
(173, 'Redeemer?s University, Mowe'),
(174, 'Renaissance University, Enugu'),
(175, 'Rivers State University of Science & Technology'),
(176, 'Salem University, Lokoja'),
(177, 'Tai Solarin Univ. of Education, Ijebu-Ode'),
(178, 'Tansian University, Umunya'),
(179, 'University of Abuja, Gwagwalada.'),
(180, 'University of Ado-Ekiti'),
(181, 'University of Agriculture, Makurdi.'),
(182, 'University of Benin.'),
(183, 'University of Calabar.'),
(184, 'University of Education, Ikere Ekiti'),
(185, 'University of Ibadan'),
(186, 'University of Ilorin'),
(187, 'University of Jos.'),
(188, 'University of Lagos.'),
(189, 'University of Maiduguri.'),
(190, 'University of Mkar, Mkar'),
(191, 'University of Nigeria, Nsukka.'),
(192, 'University of Port Harcourt.'),
(193, 'University of Uyo.'),
(194, 'Usuman Danfodiyo University.'),
(195, 'Veritas University'),
(196, 'Wesley Univ. of Science & Tech.,Ondo'),
(197, 'Western Delta University, Oghara'),
(198, 'Wukari Jubilee University'),
(199, 'Abia State University of Uturu'),
(200, 'Abti-American University, Yola'),
(201, 'Abubakar Tafawa Balewa University, Bauchi'),
(202, 'Achievers University, Owo'),
(203, 'Adamawa State University Mubi.'),
(204, 'Adekunle Ajasin University, Akungba.'),
(205, 'African University of Science & Technology, Abuja'),
(206, 'Ahmadu Bello University Zaria'),
(207, 'Ajayi Crowther University, Ibadan'),
(208, 'Akwa Ibom State University of Technology, Uyo.'),
(209, 'Al-Hikmah University, Ilorin'),
(210, 'Ambrose Ali University, Ekpoma.'),
(211, 'Anambra State University of Science and Technology, Calabar.'),
(212, 'Babcock University,Illshan-Remo'),
(213, 'Bayero University, Kano'),
(214, 'Bells University of Technology, Otta'),
(215, 'Benson Idahosa University,Benin City'),
(216, 'Benue State University, Makurdi.'),
(217, 'Bingham University, New Karu'),
(218, 'Bowen University, Iwo'),
(219, 'Buka Abba Ibrahim University, Yobe.'),
(220, 'Caleb University, Lagos'),
(221, 'Caritas University, Enugu'),
(222, 'CETEP City University, Ibadan'),
(223, 'Covenant University Ota'),
(224, 'Crawford University Igbesa'),
(225, 'Crescent University,'),
(226, 'Cross River State University of Science and Technology, Calabar.'),
(227, 'Delta State University Abraka.'),
(228, 'Ebonyi State University, Abakaliki.'),
(229, 'Enugu State University of Science and Technology, Enugu'),
(230, 'Federal University Ndufu Alike, Ebonyi.'),
(231, 'Federal University of Agriculture, Abeokuta.'),
(232, 'Federal University of Petroleum Recourses, Effurun.'),
(233, 'Federal University of Technology, Akure.'),
(234, 'Federal University of Technology, Minna.'),
(235, 'Federal University of Technology, Owerri.'),
(236, 'Federal University of Technology, Yola.'),
(237, 'Federal University Wukari, Taraba.'),
(238, 'Federal University, Dutse, Jigawa.'),
(239, 'Federal University, Dutsin?Ma-Katsina, Katsina'),
(240, 'Federal University, Lafia, Nasarawa'),
(241, 'Federal University, Lokoga, Kogi.'),
(242, 'Federal University, Otuoke, Bayelsa.'),
(243, 'Fountain Unveristy,Oshogbo'),
(244, 'Gombe State Univeristy, Gombe'),
(245, 'Ibrahim Badamasi Babangida University, Lapai'),
(246, 'Igbinedion University Okada'),
(247, 'Imo State University, Owerri'),
(248, 'Joseph Ayo Babalola University, Ikeji-Arakeji'),
(249, 'Kaduna State University, Kaduna'),
(250, 'Kano State University of Technology Wudil'),
(251, 'Katsina State University, Katsina'),
(252, 'Katsina University, Katsina'),
(253, 'Kebbi State University, Kebbi'),
(254, 'Kogi State University Anyigb'),
(255, 'Ladoke Akintola University of Technology, Ogbomoso'),
(256, 'Lagos State University Ojo, Lagos.'),
(257, 'Lead City University, Ibadan'),
(258, 'Madonna University, Okija'),
(259, 'Micheal Okpara University of Agriculture, Umudike.'),
(260, 'Nasarawa State University, Keffi'),
(261, 'National Open University of Nigeria, Lagos.'),
(262, 'Niger Delta Unversity, Yenagoa.'),
(263, 'Nigerian Defence Accademy, Kaduna.'),
(264, 'Nnamdi Azikiwe University, Akwa.'),
(265, 'Novena University, Ogume'),
(266, 'Obafemi Awolowo University, Ile Ife.'),
(267, 'Obong University'),
(268, 'Olabisi Onabanjo University Ago-Iwoye .'),
(269, 'Osun State University, Oshogbo.'),
(270, 'Pan African University, Lagos'),
(271, 'Plateau State University, Bokkos'),
(272, 'Redeemer?s University, Mowe'),
(273, 'Renaissance University, Enugu'),
(274, 'Rivers State University of Science & Technology'),
(275, 'Salem University, Lokoja'),
(276, 'Tai Solarin Univ. of Education, Ijebu-Ode'),
(277, 'Tansian University, Umunya'),
(278, 'University of Abuja, Gwagwalada.'),
(279, 'University of Ado-Ekiti'),
(280, 'University of Agriculture, Makurdi.'),
(281, 'University of Benin.'),
(282, 'University of Calabar.'),
(283, 'University of Education, Ikere Ekiti'),
(284, 'University of Ibadan'),
(285, 'University of Ilorin'),
(286, 'University of Jos.'),
(287, 'University of Lagos.'),
(288, 'University of Maiduguri.'),
(289, 'University of Mkar, Mkar'),
(290, 'University of Nigeria, Nsukka.'),
(291, 'University of Port Harcourt.'),
(292, 'University of Uyo.'),
(293, 'Usuman Danfodiyo University.'),
(294, 'Veritas University'),
(295, 'Wesley Univ. of Science & Tech.,Ondo'),
(296, 'Western Delta University, Oghara'),
(297, 'Wukari Jubilee University');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `universities`
--
ALTER TABLE `universities`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `universities`
--
ALTER TABLE `universities`
  MODIFY `id` int(255) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=298;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
